version: '3.8'
services:
  app1_container1:
    image: app1:latest
    container_name: app1_container1
    ports:
      - "7770:7770/udp"
      - "7770:7770/tcp"
    restart: unless-stopped
  app2_container1:
    image: app2:latest
    container_name: app2_container1
    ports:
      - "7771:7771/udp"
      - "7771:7771/tcp"
    restart: unless-stopped
